services:
  database:
    image: postgres:16.1-alpine
    container_name: database
    environment:
      - POSTGRES_DB=blogy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432