services:
  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306