spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

blogy:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin}
    mail: ${ADMIN_EMAIL:admin@admin.com}
  default:
    category: Uncategorized
    settings:
      title: ${BLOGY_TITLE:Sample blog title}
      description: ${BLOGY_DESCRIPTION:Sample blog description}
      url: ${BLOGY_URL:http://localhost:8080}
