spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false

blogy:
  admin:
    mail: me@ivanov.pro
    username: ivanovx
    password: ivanovx
  default:
    category: Uncategorized
    settings:
      title: Sample blog title
      description: Sample blog description
      url: http://localhost:8080