spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/blogy}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            directory.root: ./data/index

blogy:
  admin:
    username: ivanovx
    password: ivanovx
    mail: me@ivanov.pro
  default:
    category: Uncategorized
    settings:
      title: Sample blog title
      description: Sample blog description
      url: http://localhost:8080
