#spring:
#  datasource:
#    url: jdbc:mysql://db:3306/blog
#    username: root
#    password: root
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#    open-in-view: false